from turtle import *

# Thiết lập màn hình
window = Screen()
window.bgcolor("lightgreen")  # Màu nền xanh nhạt
control = Turtle()
control.speed(40)  # Tốc độ vẽ chậm hơn để dễ quan sát


control.penup()
control.goto(0, 200)
control.pendown()

control.begin_fill()
control.color("pink")
control.forward(500)
control.right(45)
control.forward(80)
control.right(135)
control.forward(600)
control.right(125)
control.forward(79)
control.end_fill()

control.penup()
control.goto(0, 142)
control.pendown()

control.begin_fill()
control.color("red")
control.right(145)
control.forward(200)
control.left(90)
control.forward(500)
control.left(90)
control.forward(200)
control.end_fill()

control.penup()
control.goto(90, 50)
control.pendown()

control.begin_fill()
control.color("yellow")
for i in range (4):
    control.forward(50)
    control.left(90)
control.end_fill()

control.penup()
control.goto(450, 50)
control.pendown()

control.begin_fill()
control.color("yellow")
for i in range (4):
    control.forward(50)
    control.left(90)
control.end_fill()

control.penup()
control.goto(260, 50)
control.pendown()

control.begin_fill()
control.color("yellow")
control.forward(5)
control.left(90)
control.forward(50)
control.left(90)
control.forward(113)
control.left(90)
control.forward(50)
control.left(90)
control.forward(113)
control.end_fill()

control.penup()
control.goto(0, 350)
control.pendown()

control.begin_fill()
control.color("white")
control.right(90)
control.forward(75)
control.circle(35, 105)
control.right(30)
control.forward(10)
control.circle(35, 105)
control.circle(35, 105)
control.right(180)
control.circle(35, 105)
control.circle(35, 105)
control.forward(30)
control.end_fill()

control.penup()
control.goto(400, 330)
control.pendown()

control.begin_fill()
control.color("white")
control.left(40)
control.forward(75)
control.circle(35, 105)
control.right(30)
control.forward(10)
control.circle(35, 105)
control.circle(35, 105)
control.right(180)
control.circle(35, 105)
control.circle(35, 105)
control.forward(30)
control.end_fill()

control.penup()
control.goto(500, 330)
control.pendown()

control.begin_fill()
control.color("yellow")
control.circle(40)
control.end_fill()

control.penup()
control.goto(-500, -500)
control.pendown()

control.begin_fill()
control.color("blue")
control.left(150)
control.forward(1200)
control.left(90)
control.forward(200)
control.left(90)
control.forward(1200)
control.end_fill()

control.penup()
control.goto(0, -440)
control.pendown()

control.begin_fill()
control.color("blue")
control.left(80)
control.forward(300)
control.left(90)
control.forward(40)
control.left(50)
control.forward(30)
control.left(40)
control.forward(50)
control.right(50)
control.forward(40)
control.left(40)
control.forward(60)
control.left(40)
control.forward(70)
control.right(19)
control.forward(60)
control.left(43)
control.forward(50)
control.end_fill()

control.penup()
control.goto(40, -440)
control.pendown()

control.begin_fill()
control.color("black")
control.circle(20)
control.end_fill()

control.penup()
control.goto(220, -440)
control.pendown()

control.begin_fill()
control.color("black")
control.circle(20)
control.end_fill()

control.penup()
control.goto(150, -350)
control.pendown()

control.begin_fill()
control.color("white")
for i in range(3):
    control.left(20)
    control.forward(30)
    control.left(90)
control.end_fill()

control.penup()
control.goto(-400, -400)
control.pendown()

control.begin_fill()
control.color("brown")
control.right(20)
control.forward(50)
control.right(90)
control.forward(200)
control.right(90)
control.forward(50)
control.right(90)
control.forward(200)
control.end_fill()

control.penup()
control.goto(-400, -200)
control.pendown()
control.begin_fill()
control.color("black","green")
control.circle(50)
control.end_fill()

control.penup()
control.goto(-450, -200)
control.pendown()

control.begin_fill()
control.circle(50)
control.end_fill()

control.penup()
control.goto(-550, -180)
control.pendown()

control.begin_fill()
control.circle(50)
control.end_fill()

control.penup()
control.goto(-500, -150)
control.pendown()

control.begin_fill()
control.circle(50)
control.end_fill()

control.penup()
control.goto(-450, -160)
control.pendown()

control.begin_fill()
control.circle(50)
control.end_fill()

control.penup()
control.goto(-150, 100)
control.pendown()

control.begin_fill()
control.color("black")
control.circle(20)

control.end_fill()

control.penup()
control.goto(-130, 100)
control.pendown()
control.forward(100)
control.right(45)
control.forward(30)

window.mainloop()
