from turtle import *
window = Screen()
control = Turtle()
control.speed(500)
control.begin_fill()
control.color("red", "red")
for i in range(3):
    control.forward(100)
    control.left(120)
control.end_fill()

control.penup()
control.goto(-20, 110)
control.pendown()

control.forward(150)
control.right(90)
control.forward(65)
control.left(90)
control.forward(20)
control.left(90)
control.forward(30)
control.left(-120)
control.forward(90)
control.left(-120)
control.forward(90)
control.right(120)
control.forward(30)
control.left(90)
control.forward(20)
control.left(90)
control.forward(65)
control.right(90)
control.forward(150)
control.right(90)
control.forward(160)

control.penup()
control.goto(-500, 110)
control.pendown()

control.begin_fill()
control.color("green")
control.forward(200)
control.left(90)
control.forward(400)
control.left(90)
control.forward(200)
control.left(90)
control.forward(400)
control.left(90)
control.forward(100)
control.right(90)
control.forward(140)
control.right(90)
control.forward(100)
control.right(90)
control.forward(140)
control.end_fill()

control.penup()
control.goto(-650, 150)
control.pendown()

control.begin_fill()
control.color("red")
control.right(90)
control.forward(40)
control.right(90)
control.forward(30)
control.left(90)
control.forward(10)
control.left(90)
control.forward(10)
control.right(135)
control.forward(30)
control.right(90)
control.forward(30)
control.left(225)
control.forward(10)
control.left(90)
control.forward(10)
control.left(90)
control.forward(30)
control.right(90)
control.forward(40)
control.right(90)
control.forward(80)
control.end_fill()

control.penup()
control.goto(-850, 150)
control.pendown()

control.begin_fill()
control.color("red")
control.right(90)
control.forward(40)
control.right(90)
control.forward(30)
control.left(90)
control.forward(10)
control.left(90)
control.forward(10)
control.right(135)
control.forward(30)
control.right(90)
control.forward(30)
control.left(225)
control.forward(10)
control.left(90)
control.forward(10)
control.left(90)
control.forward(30)
control.right(90)
control.forward(40)
control.right(90)
control.forward(80)
control.end_fill()

control.penup()
control.goto(-790, 110)
control.pendown()

control.begin_fill()
control.color("blue")
control.circle(30)
control.end_fill()

control.penup()
control.goto(-790, 90)
control.pendown()

control.begin_fill()
control.color("white")
control.circle(8)
control.end_fill()


control.penup()
control.goto(-590, 110)
control.pendown()

control.begin_fill()
control.color("blue")
control.circle(30)
control.end_fill()

control.penup()
control.goto(-590, 90)
control.pendown()

control.begin_fill()
control.color("white")
control.circle(8)
control.end_fill()

window.mainloop()